AWSTemplateFormatVersion: '2010-09-09'
Description: >
  mysterio

  SAM Template for mysterio
Parameters:
  IAMUsername:
    Description: Name of the IAM user who will be the administrator of the KMS key
      we create. This user will be able to encrypt values and manage the key.
    Type: String
    Default: alam
Resources:
  PTOBalancesFunction:
    Properties:
      CodeUri: ./
      Description: AWS Lambda Function used as a wrapper for a tsheet api request
      FunctionName: PTOBalancesFunction
      Handler: app-pto-balances.lambdaHandler
      Role:
        Fn::GetAtt:
          - PTOBalancesFunctionRole
          - Arn
      Runtime: nodejs12.x
      Timeout: 30
      Events:
        PTOBalances:
          Type: Api
          Properties:
            Path: /pto-balances/{employeeNumber}
            Method: get
    Type: AWS::Serverless::Function
  PTOBalancesFunctionRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: '2012-10-17'
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ssm:GetParameter*
                Effect: Allow
                Resource:
                  Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/TSheets/accessToken
            Version: '2012-10-17'
          PolicyName: PTOBalancesParameterAccess
        - PolicyDocument:
            Statement:
              - Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: '*'
            Version: '2012-10-17'
          PolicyName: PTOBalancesLambdaBasicExecution
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PTOBalancesApi:
    Description: 'API Gateway endpoint URL for Prod stage for PTO Balances function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pto-balances/'
  PTOBalancesFunction:
    Description: 'PTO Balances Lambda Function ARN'
    Value: !GetAtt PTOBalancesFunction.Arn
  PTOBalancesFunctionIamRole:
    Description: 'Implicit IAM Role created for PTO Balances function'
    Value: !GetAtt PTOBalancesFunctionRole.Arn
