version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mysterio"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-of56hkvz9asj"
s3_prefix = "mysterio"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
