version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mysterio"
s3_bucket = "mysterio-aws-sam-cli"
s3_prefix = "mysterio"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
